apiVersion: v2
name: alexander
description: A Helm chart for Alexander Storage - S3-compatible object storage server

type: application

version: 0.1.0

appVersion: "1.0.0"

keywords:
  - s3
  - object-storage
  - storage
  - minio-alternative
  - backup

home: https://github.com/neuralforgeone/alexander-storage

sources:
  - https://github.com/neuralforgeone/alexander-storage

maintainers:
  - name: neuralforgeone
    url: https://github.com/neuralforgeone

annotations:
  artifacthub.io/license: MIT
  artifacthub.io/category: storage
