{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexander.fullname" . }}
  labels:
    {{- include "alexander.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.masterKey }}
  ALEXANDER_AUTH_MASTER_KEY: {{ .Values.secrets.masterKey | quote }}
  {{- end }}
  {{- if .Values.secrets.sseMasterKey }}
  ALEXANDER_AUTH_SSE_MASTER_KEY: {{ .Values.secrets.sseMasterKey | quote }}
  {{- end }}
  {{- if and (eq .Values.config.database.driver "postgres") .Values.secrets.database.user }}
  ALEXANDER_DATABASE_USER: {{ .Values.secrets.database.user | quote }}
  {{- end }}
  {{- if and (eq .Values.config.database.driver "postgres") .Values.secrets.database.password }}
  ALEXANDER_DATABASE_PASSWORD: {{ .Values.secrets.database.password | quote }}
  {{- end }}
  {{- if and .Values.config.redis.enabled .Values.secrets.redis.password }}
  ALEXANDER_REDIS_PASSWORD: {{ .Values.secrets.redis.password | quote }}
  {{- end }}
{{- end }}
